language: android
jdk: oraclejdk8

# Needed for constraintlayout - https://code.google.com/p/android/issues/detail?id=212128
before_install:
  - yes | sdkmanager --licenses

install:
  skip

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository

before_script:

script:
  # Workaround for constraintlayout - https://code.google.com/p/android/issues/detail?id=212128
  - ./gradlew dependencies || true && ./gradlew buildRelease testReleaseUnitTest